---
title: "Massachusetts_Cleaning_Data.Rmd"
author: "Emma Wellbaum"
date: "4/17/2021"
output: html_document
editor_options:
  chunk_output_type: console
---

###
This file is for taking the downloaded ebird data and processing it into summary files. 

NOTE:

I will use 4-letter AOU Bird Codes to refer to species in R. For reference:

Red-winged Blackbird = RWBL
Osprey = OSPR
Wood Duck = WODU

(https://www.birdpop.org/pages/birdSpeciesCodes.php)

## Set up

```{r setup, include=FALSE}
getwd()

#install.packages("auk")
library(auk)
library(tidyr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(viridis)
library(cowplot)

#Set theme
mytheme <- theme_bw(base_size = 14) + 
  theme(legend.position = 'right')
theme_set(mytheme)
```

## Summarize State Temperature Data

```{r temp.data.analysis}
# Import state temperature data, downloaded from the National Atmospheric and
# Oceanic Administration using the rnoaa package
MA_temp <- read.csv('./Data/Raw/Massachusetts/MassTemperature20102021.csv') %>% unique()

# Summarize monthly temperature data for the entire state
MA_temp_state <- MA_temp %>%
  mutate(Month_Year = paste0(Month,'-',Year)) %>% 
  mutate(Month_Year = my(Month_Year)) %>%
  drop_na(AvgMonthlyTemp) %>% 
  group_by(Month_Year) %>% 
  summarize(AvgMonthlyTemp_F = mean(AvgMonthlyTemp))
```

## Import Bird Data

```{r include=FALSE}
# Import data downloaded from eBird and filter for columns and rows of interest
OSPR <- read_ebd(
  "./Data/Raw/Massachusetts/ebd_US-MA_osprey_relFeb-2021/ebd_US-MA_osprey_relFeb-2021.txt")
RWBL <- read_ebd(
  "./Data/Raw/Massachusetts/ebd_US-MA_rewbla_201001_202102_relMar-2021/ebd_US-MA_rewbla_201001_202102_relMar-2021.txt")
WODU <- read_ebd(
  "./Data/Raw/Massachusetts/ebd_US-MA_wooduc_relFeb-2021/ebd_US-MA_wooduc_relFeb-2021.txt")

#Create a merged dataset with all three species
MAbirds <- bind_rows(OSPR, RWBL, WODU)
```


## Wrangle Data

```{r include=FALSE}
MAbirds <- MAbirds %>% 
  select(common_name:observation_count, state, county, latitude:observation_date, protocol_type,duration_minutes:all_species_reported) %>% 
  mutate(Month_Year = floor_date(observation_date, unit = "month"),
         Week = floor_date(observation_date, unit = "week"),
         Presence = 1,
         observation_count = as.numeric(replace(observation_count, observation_count == 'X', '1')),
         observations_per_min = observation_count/duration_minutes) %>% 
  filter(year(observation_date) %in% c(2010:2021)) %>%
  arrange(Month_Year, Week)

# Examine the merged dataset
summary(MAbirds$observations_per_min)

#Join monthly temperature data to bird observation data
MAbirds <- merge(x=MAbirds, y=MA_temp_state, by='Month_Year', all.x=TRUE)

#Filter the dataset for valid observational effort (remove NAs)
MAbirds_obs <- MAbirds %>% 
  filter( is.na(observations_per_min) == FALSE) %>% 
  filter( observations_per_min != Inf)

#Confirm the filtered dataset does not have NA or infinite values
summary(MAbirds_obs$observations_per_min)

#Summarize the number of observations by month
MAbirds_month <- MAbirds_obs %>% 
  group_by(Month_Year, common_name, state) %>% 
  summarize(ObservationE = mean(observations_per_min),
            Presence = sum(Presence),
            Observations = sum(observation_count),
            AvgMonthlyTemp_F = mean(AvgMonthlyTemp_F)) %>%
  select(common_name, state, Observations, ObservationE, Presence, Month_Year, AvgMonthlyTemp_F)

#Summarize the number of observations by week
MAbirds_week <- MAbirds_obs %>%
  group_by(Week, Month_Year, common_name, state) %>% 
  summarize(ObservationE = mean(observations_per_min),
            Presence = sum(Presence),
            Observations = sum(observation_count),
            AvgWeeklyTemp_F = mean(AvgMonthlyTemp_F)) %>%
  mutate(Month = month(Week),
         Year = year(Week)) %>% 
  filter(Year %in% c(2010:2020)) %>% 
  select(common_name, state, Observations, ObservationE, Presence, Week, Month, Year, Month_Year, AvgWeeklyTemp_F)
```


## Plot Data

```{r monthly.sum.plots}
#Plot Average Observations per Minute for 2010-2021 for All Species
ggplot(MAbirds_month, 
       aes(x=Month_Year, y=log(ObservationE), color=AvgMonthlyTemp_F)) +
  geom_line(lwd=0.8) +
  geom_hline(yintercept=-1.5, lty=2) +
  scale_color_viridis(option='plasma') +
  scale_x_date(date_breaks = '1 year', date_labels = '%Y') +
labs(x='Year', y='Average Observations per Minute of Observation (log10)', color='Mean Temperature (F)', title= 'Massachusets Bird Observations: 2010-2021', subtitle = 'by Average Monthly Temperature (F)') +
  facet_wrap(~common_name, nrow=3)


#Plot Average Observations per Minute by Year and Species: Osprey
OSPRplot <- ggplot(filter(MAbirds_month, common_name == 'Osprey'), aes(x=month(Month_Year), y=log(ObservationE), group=year(Month_Year), color=AvgMonthlyTemp_F)) +
  geom_line(lwd=0.8) +
  #geom_smooth(method='lm', se=F, color='black', lwd=0.6) +
  scale_color_viridis(option='plasma') + 
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(expand = c(0,0), breaks = c(1, 4, 8, 12), labels = c('Jan','Apr', 'Aug', 'Dec')) +
labs(x='', y='Average Observations per Minute of Observation (log10)', color='Mean Temperature (F)', title = 'Osprey') +
  theme(legend.position='none', title=element_text(size=12)) +
  facet_grid(vars(year(Month_Year)))


#Plot Average Observations per Minute by Year and Species: Red-winged Blackbird
RWBLplot <- ggplot(filter(MAbirds_month, common_name == 'Red-winged Blackbird', year(Month_Year) <2021), aes(x=month(Month_Year), y=log(ObservationE), group=year(Month_Year), color=AvgMonthlyTemp_F)) +
  geom_line(lwd=0.8) +
  #geom_smooth(method='lm', se=F, color='black', lwd=0.6) +
  scale_color_viridis(option='plasma') + 
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(expand = c(0,0), breaks = c(1, 4, 8, 12), labels = c('Jan','Apr', 'Aug', 'Dec')) +
labs(x='', y='', color='Mean Temperature (F)', title='Red-winged Blackbird') +
  theme(legend.position='bottom', title=element_text(size=12)) +
  facet_grid(vars(year(Month_Year)))


#Plot Average Observations per Minute by Year and Species: Wood Duck
WODUplot <- ggplot(filter(MAbirds_month, common_name == 'Wood Duck', year(Month_Year) <2021), aes(x=month(Month_Year), y=log(ObservationE), group=year(Month_Year), color=AvgMonthlyTemp_F)) +
  geom_line(lwd=0.8) +
  #geom_smooth(method='lm', se=F, color='black', lwd=0.6) +
  scale_color_viridis(option='plasma') + 
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(expand = c(0,0), breaks = c(1, 4, 8, 12), labels = c('Jan','Apr', 'Aug', 'Dec')) +
labs(x='', y='', color='Mean Temperature (F)', title='Wood Duck') +
  theme(legend.position='none', title=element_text(size=12)) +
  facet_grid(vars(year(Month_Year)))

tempplot <- plot_grid(OSPRplot, RWBLplot + theme(legend.position='none'), WODUplot, nrow=1)

legendplot <- get_legend(RWBLplot + theme(legend.position='right', plot.margin=margin(7, 0, 0, 0)))

title <- ggdraw() + 
  draw_label('Seasonal Stay in Massachusetts by Species',
             fontface = 'bold',
             x = 0,
             hjust = 0) +
  theme(plot.margin = margin(0, 0, 0, 5))

tplot <- plot_grid(title, tempplot, ncol = 1, rel_heights = c(.08, 1))

finalplot <- plot_grid(tplot, legendplot, nrow=1, rel_widths = c(1, .2))

print(finalplot)
```


```{r weekly.sum.plots}
#Plot Average Observations per Minute for 2010-2021 for All Species
ggplot(MAbirds_week, 
       aes(x=Week, y=log(ObservationE), color=AvgWeeklyTemp_F)) +
  geom_line(lwd=0.8) +
  geom_hline(yintercept=-2, lty=2) +
  scale_color_viridis(option='plasma') +
  scale_x_date(date_breaks = '1 year', date_labels = '%Y') +
labs(x='Year', y='log(Observations/Min)', color='Mean Temperature (F)', title= 'Average Observations per Minute of Observation: 2010-2021', subtitle = 'Massachusetts') +
  theme(legend.position = 'bottom') +
  facet_wrap(~common_name, nrow=3)


#Plot Seasonal Stay in Massachusetts by Species and Year
ggplot(MAbirds_week) +
  geom_smooth(aes(x=month(Week), y=log(ObservationE), color=common_name), method='loess', se=F, lwd=0.8) +
  scale_color_manual(values=c('#1E88E5', '#D81B60', '#004D40')) + 
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(expand = c(0,0), breaks = c(1, 4, 8, 12), labels = c('Jan','Apr', 'Aug', 'Dec')) +
labs(x='', y='', color='', title='Seasonal Stay by Species Over Time', subtitle = 'Massachusetts') +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), panel.spacing.x = unit(2, 'lines')) +
  facet_grid(vars(year(Week)), vars(common_name))
```
